name: Deploy Ask Alice Backend

on:
  push:
    branches:
      - main
    paths:
      - '**'  # Trigger on any file change
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ask-alice-chatbot
        package: backend
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

